library(shiny)
library(lubridate)

shinyUI(fluidPage(
    titlePanel("Product Development - Lab No. 1 Deyanira Aguilar 19004789"),
    sidebarLayout(
        sidebarPanel(
            sliderInput("Slider_input",
                        "Seleccione valor:",
                        value = 50,
                        min = 0,
                        max = 100,
                        step = 10,
                        post = '%',
                        animate = TRUE),
            sliderInput("Slider_input_2",
                        "Seleccione un rango:",
                        value = c(0, 200),
                        min = 0,
                        max = 200,
                        step = 10,
                        animate = TRUE),
            selectInput("select_input",
                        "Seleccione un auto:",
                        choices = rownames(mtcars),
                        selected = "Camaro Z28",
                        multiple = FALSE),
            selectizeInput("select_input_2",
                           "Seleccione autos:",
                           choices = rownames(mtcars),
                           selected = "Camaro Z28",
                           multiple = TRUE),
            dateInput("date_input",
                      "Ingrese la fecha",
                      value = today(),
                      min = today()-60,
                      max = today()+30,
                      language = "es",
                      weekstart = 1,
                      format = "yyyy-mm-dd"),
            dateRangeInput("date_range",
                           "Ingrese fechas",
                           start = today()-7,
                           end = today(),
                           separator = 'a'),
            numericInput("numeric_input",
                         "Ingrese un número:",
                         value = 10,
                         min = 0,
                         max = 100,
                         step = 1),
            checkboxInput("single_box",
                          "Seleccione si verdadero",
                          value = FALSE),
            checkboxGroupInput("group_box",
                               "Seleccione opciones:",
                               choices = LETTERS[1:5]),
            radioButtons("radio_ex",
                         "Seleccione género",
                         choices = c("F", "M")),
            textInput("text_input",
                      "Ingrese texto:"),
            textAreaInput("text_area",
                          "Ingrese parrafo"),
            actionButton("action_button",
                         "Ok"),
            actionLink("action_link",
                       "Siguiente"),
            submitButton(text = "Reprocesar")
        ),

        mainPanel(
            h2("Slider input sencillo"),
            verbatimTextOutput("slider_io"),
            h2("Slider input rango"),
            verbatimTextOutput("slider_io_2"),
            h2("Select input"),
            verbatimTextOutput("select_io"),
            h2("Select input multiple"),
            verbatimTextOutput("select_io_multi"),
            h2("Fecha"),
            verbatimTextOutput("date_io"),
            h2("Rango de fechas"),
            verbatimTextOutput("range_io"),
            h2("Numeric input"),
            verbatimTextOutput("numeric_io"),
            h2("Single checkbox"),
            verbatimTextOutput("single_box_io"),
            h2("Grouped checkbox"),
            verbatimTextOutput("multiple_box_io"),
            h2("Radio buttons"),
            verbatimTextOutput("radio_io"),
            h2("Texto"),
            verbatimTextOutput("text_io"),
            h2("Parrafo"),
            verbatimTextOutput("text_area_io"),
            h2("Action button"),
            verbatimTextOutput("action_bt_io"),
            h2("Action link"),
            verbatimTextOutput("action_link_io")
        )
    )
))
